export const LINKS = {
  NL: {
    HOME: "/nl",
    ABOUT: "/nl/over-ons",
    GAME_OVERVIEW: "/nl/escape-room",
    TEAMBUILDING: "/nl/teambuilding-events",
    CONTACT: "/nl/contact",
    AWARDS: "/nl/awards",
    NEWS: "/nl/nieuws",
    PERS: "/nl/pers",
    GIFTCARD: "/nl/cadeaubon",
    FAQ: "/nl/faq",
    BOOK: "/nl/boeking",
    PRIVACY: "/nl/privacy",
    ACTIVITY_DEALS: "/nl/activiteiten-in-mechelen",
    RESTAURANT_DEALS: "/nl/hapje-eten",
    HOTEL_DEALS: "/nl/hotels-in-mechelen",
    RESERVE: "/nl/boeking",
    JOBS: "/nl/jobs",
  },
  EN: {
    HOME: "/en",
    ABOUT: "/en/about-us",
    GAME_OVERVIEW: "/en/overview",
    TEAMBUILDING: "/en/teambuilding-events",
    CONTACT: "/en/contact",
    AWARDS: "/en/awards",
    NEWS: "/en/news",
    GIFTCARD: "/en/giftcard",
    FAQ: "/en/faq",
    BOOK: "/en/reserve",
    PRIVACY: "/en/privacy",
    PERS: "/en/pers",
    ACTIVITY_DEALS: "/en/activities",
    RESTAURANT_DEALS: "/en/grab-a-bite",
    HOTEL_DEALS: "/nl/hotels-in-mechelen",
    RESERVE: "/en/reserve",
    JOBS: "/en/jobs",
  },
};
