export const LINKS = {
  NL: {
    HOME: "/nl",
    ABOUT: "/nl/over-ons",
    GAME_OVERVIEW: "/nl/overzicht",
    TEAMBUILDING: "/nl/teambuilding-events",
    CONTACT: "/nl/contact",
    AWARDS: "/nl/awards",
    NEWS: "/nl/nieuws",
    PERS: "/nl/pers",
    GIFTCARD: "/nl/shop",
    FAQ: "/nl/faq",
    BOOK: "/nl/boek-nu",
    PRIVACY: "/nl/privacy",
    ACTIVITY_DEALS: "/nl/activiteiten-in-mechelen",
    RESTAURANT_DEALS: "/nl/hapje-eten",
  },
  EN: {
    HOME: "/en",
    ABOUT: "/en/about-us",
    GAME_OVERVIEW: "/en/overview",
    TEAMBUILDING: "/en/teambuilding-events",
    CONTACT: "/en/contact",
    AWARDS: "/en/awards",
    NEWS: "/en/news",
    GIFTCARD: "/en/shop",
    FAQ: "/en/faq",
    BOOK: "/en/book-now",
    PRIVACY: "/en/privacy",
    PERS: "/en/pers",
    ACTIVITY_DEALS: "/en/activities",
    RESTAURANT_DEALS: "/en/grab-a-bite",
  },
};
