import { Inter } from "next/font/google";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import "./globals.css";
import "./slick.css";
import { Footer, MegaMenu, TopBar } from "@/components/organisms";
import React from "react";

const font = Inter({
  subsets: ["latin"],
  weight: ["300", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>
        <TopBar />
        <MegaMenu />
        {children}
        <Footer />
      </body>
    </html>
  );
}
